baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
enableGitInfo = true

[menus]
  [[menus.main]]
    name = '<u>H</u>ome'
      url = "/"
      weight = 1
  [[menus.main]]
      name = '<u>T</u>ags'
      url = '/tags'
      weight = 3

[params]
  description = 'Hugo dead simple example'

[module]
  [[module.imports]]
    path = 'github.com/barklan/hugo-dead-simple'